### ISSUE TITLE
The script doesn't break the loop when password has been cracked

### ISSUE THREAD

**Issue by NOMADooo** [mtagius/pwnagotchi-tools#3]
The script is continuing to run all the attacks (doesn't break the loop) even though the cracked password is visible in "print_final_results.py", "hashcat-output.txt" , "hashcat-potfile.txt".

**Comment by mtagius** [comment]
This is by design. After a password is found while running an attack script Hashcat saves the password to "hashcat-potfile.txt". The attack script will continue and start all remaining attacks, but Hashcat will see the password in the potfile and immediately end the attack. So, even if the password was found in the first attack in the script it would only take a few minutes for the remaining attacks to start and then terminate early, leaving you with the password. While the attack script could first check if a password has been found before running the next Hashcat command, I did not see much value to do so.

Is this the behaviour you are seeing or is there another problem?

**Comment by NOMADooo** [comment]
Password was very simple (123456789) and it was found after few secs. (20:00) But hashcat kept going through other attacks and finished at 8:00 so after 12 hours of useless password cracking because the password has been cracked before. I've pressed the .bat file only for one AP, I didn't run the batch - maybe there is a problem? Tbh. It should stop in the case after the password has been cracked and there are no more remaining APs to be attacked.
Can you give me a clue how can I look through the logs or maybe even upload them here?
Cause I can only see 1 log file per every attack so there are currently 62 files that I don't want to look through it by hand.

**Comment by mtagius** [comment]
Ah, I see. Yeah, that sucks you had to waste all that cracking time. So, let's clarify a few things. 

By running generate-hashcat-scripts.py .bat files will be generated for each AP and 1 batch file will be made in the batches folder. The batch file just has a list of all the .bat files generated from when generate-hashcat-scripts.py was run. Using the batch file is optional and is only used if you want to run all the .bat AP files sequentially instead of having to manually start each .bat file.

Hashcat keeps track of passwords it has already cracked in hashcat-potfile.txt. Each of the hashcat commands used give that file as an argument to ensure hashcat always uses the same potfile. If hashcat is started and the AP and its password are in the potfile then it will stop automatically. Because of this feature of hashcat my code does not monitor if the password is cracked because the rest of the hashcat commands would just end immediately. So, yes, this project does stop when the password has been found.

If hashcat kept running for you then a few things could have gone wrong:
- hashcat can't find the potfile. Can you see the potfile and is the filepath in the .bat file correct?
- The target file still had something hashcat was trying to crack. While the pwnagotchi separates the .pcap files based on AP, it's possible that one pcap can have several handshakes in it. As a result, after the first password was found, there may have been more passwords that hashcat was trying to crack. If you run any of the commands from the .bat file you used what does hashcat say in the "recovered" section?

This project does not produce logs and hashcat logs probably won't help much here.

**Comment by NOMADooo** [comment]
Yes, the potfile is visible and the path in a .bat file is correct.
Ohhh you're right - it says 1/2 Digests is recovered. so the hashcat tried to crack the second handshake I've captured.
Thank you for clarifying those things!
